### ISSUE TITLE
Can it be possible to detect edge of document on any surface

### ISSUE THREAD

**Issue by patelranjit** [adityaarora1/LiveEdgeDetection#11]
Currently the edge of document is detecting on only dark background, but it ll be more useful if it can detect on any surface.

**Comment by adityaarora1** [comment]
It is currently a limitation of the algorithm.

**Comment by rodimus-11** [comment]
Any update on this ?? Or could you point to places within the library wherein changes have to be made to include all types of backgrounds ?
