### ISSUE TITLE
Is it possible to make it work with white background or else ?

### ISSUE THREAD

**Issue by ManuSynert** [adityaarora1/LiveEdgeDetection#12]
Hi, Is it possible to make it work with white background or something else ? where should I modify the code to make changes ?

**Comment by adityaarora1** [comment]
The current implementation is restricted to dark background only due to algorithm constraints.

**Comment by ManuSynert** [comment]
Okey . And the implementation doesn't work : 
"Failed to resolve: com.github.adityaarora1:LiveEdgeDetection:1.0.6"
What can I do ?
