### ISSUE TITLE
Android implementation doesn't work

### ISSUE THREAD

**Issue by ManuSynert** [adityaarora1/LiveEdgeDetection#13]
I added :
"implementation 'com.github.adityaarora1:LiveEdgeDetection:1.0.6' "
And that doesn't work, I have this message : "Failed to resolve: com.github.adityaarora1:LiveEdgeDetection:1.0.6"

I don't want to add the entire folder in my project , It's maybe a versioning problem ?

**Comment by grig-ian-theo** [comment]
i downloaded this lib from github(version 1.6), and remove icons from manifest, and it started work

**Comment by schrockblock** [comment]
I had this same problem. No matter what version I chose, it would always fail to resolve. Eventually I used `implementation 'com.github.adityaarora1:LiveEdgeDetection:master-SNAPSHOT'` and that worked.

**Comment by zakblacki** [comment]
> implementation 'com.github.adityaarora1:LiveEdgeDetection:master-SNAPSHOT'

It didn't work either ...

**Comment by DerrickRocha** [comment]
I tried schrockblocks solution and I keep getting the following error when trying to start the scanner:
"No implementation found for void org.opencv.imgproc.Imgproc.Canny_3(long, long, double, double) (tried Java_org_opencv_imgproc_Imgproc_Canny_13 and Java_org_opencv_imgproc_Imgproc_Canny_13__JJDD)"

**Comment by adityaarora1** [comment]
Check latest and open a new issue if it still persists.

**Comment by ctsandroid** [comment]
"implementation 'com.github.adityaarora1:LiveEdgeDetection:1.0.6' "
And that doesn't work, I have this message : "Failed to resolve: com.github.adityaarora1:LiveEdgeDetection:1.0.6"

facing same issue still can you plz help me out
