### ISSUE TITLE
Bad quality of image

### ISSUE THREAD

**Issue by AlexanderBykin** [adityaarora1/LiveEdgeDetection#17]
Hi
After the photo is taken it is have poor quality, how to improve the quality?
Impossible to read text

**Comment by AlexanderBykin** [comment]
Here is image taken with this library, i think it is very bad idea to resize resulting image to Display resolution as it did in this library
[LiveEdgeDetection bad quality](https://yadi.sk/i/KtX870SkCblhFg)

**Comment by pavlo-hrytsiuk** [comment]
Hello
I found that picture size set at ScanSurfaceView in surfaceChanged method,
I changed it on:
     // Camera.Size size = ScanUtils.determinePictureSize(camera, parameters.getPreviewSize());
        Camera.Size size2 = ScanUtils.getOptimalPictureSize(camera, width, height,  parameters.getPreviewSize());

it works better

**Comment by AlexanderBykin** [comment]
@PavloHrytsiuk 
thanks neighbour :)

**Comment by alexxrealpee** [comment]
@AlexanderShniperson @PavloHrytsiuk Can the resolution of the image be further improved? I'm looking to scan documents in small print, thanks.

**Comment by Kampijo** [comment]
@alexxrealpee in onPictureClicked callback, it resizes the image based on the width and height of the window.
If you want a high quality image, it's best to remove that line.
You could also change the way its saving into internal directory as it currently compresses in JPEG format.

**Comment by zakblacki** [comment]
> @alexxrealpee in onPictureClicked callback, it resizes the image based on the width and height of the window.
> If you want a high quality image, it's best to remove that line.
> You could also change the way its saving into internal directory as it currently compresses in JPEG format.

what do you mean by that how do I do that ?

**Comment by adityaarora1** [comment]
Image size can be customized as suggested by @Kampijo
