### ISSUE TITLE
Is it possible to turn off auto snapping ??

### ISSUE THREAD

**Issue by darohar** [adityaarora1/LiveEdgeDetection#19]

**Comment by jasoncool** [comment]
u can add a boolean value isOpenAtuoCaptrue at 
 if (!isAutoCaptureScheduled&&isOpenAtuoCaptrue) {
                    scheduleAutoCapture(scanHint);
                }
int ScanSurfaceView.java

**Comment by zakblacki** [comment]
> u can add a boolean value isOpenAtuoCaptrue at
> if (!isAutoCaptureScheduled&&isOpenAtuoCaptrue) {
> scheduleAutoCapture(scanHint);
> }
> int ScanSurfaceView.java

I didn't get the 
"int ScanSurfaceView.java" ??

**Comment by jasoncool** [comment]
> > u can add a boolean value isOpenAtuoCaptrue at
> > if (!isAutoCaptureScheduled&&isOpenAtuoCaptrue) {
> > scheduleAutoCapture(scanHint);
> > }
> > int ScanSurfaceView.java
> 
> I didn't get the
> "int ScanSurfaceView.java" ??

in the ScanSurfaceView.java
sorry，打错了 
你自己翻译一下
就是在ScanSurfaceView这个类中加一个布尔值，然后根据布尔值来控制是否自动捕捉画面。
 com.adityaarora.liveedgedetection.view.ScanSurfaceView;

**Comment by zakblacki** [comment]
> > > u can add a boolean value isOpenAtuoCaptrue at
> > > if (!isAutoCaptureScheduled&&isOpenAtuoCaptrue) {
> > > scheduleAutoCapture(scanHint);
> > > }
> > > int ScanSurfaceView.java
> > 
> > 
> > I didn't get the
> > "int ScanSurfaceView.java" ??
> 
> in the ScanSurfaceView.java
> sorry，打错了
> 你自己翻译一下
> 就是在ScanSurfaceView这个类中加一个布尔值，然后根据布尔值来控制是否自动捕捉画面。
> com.adityaarora.liveedgedetection.view.ScanSurfaceView;

Can you give exemple how you used to call

`startActivityForResult(new` Intent(this, ScanActivity.class), REQUEST_CODE); 
`String` filePath = `data.getExtras().getString(ScanConstants.SCANNED_RESULT); 
`Bitmap` baseBitmap = `ScanUtils.decodeBitmapFromFile(filePath,` ScanConstants.IMAGE_NAME);
in your project method
