### ISSUE TITLE
FATAL EXCEPTION: main on Moto Xstyle Running Android 7.0

### ISSUE THREAD

**Issue by nikunjgundaniya** [adityaarora1/LiveEdgeDetection#2]
`Process: com.adityaarora.liveedgedetection, PID: 10440`
`java.lang.RuntimeException: takePicture failed`
    `at android.hardware.Camera.native_takePicture(Native Method)`
    `at android.hardware.Camera.takePicture(Camera.java:1461)`
    `at android.hardware.Camera.takePicture(Camera.java:1406)`
    `at com.adityaarora.liveedgedetection.view.ScanSurfaceView.autoCapture(ScanSurfaceView.java:313)`
    `at com.adityaarora.liveedgedetection.view.ScanSurfaceView.access$500(ScanSurfaceView.java:43)`
    `at com.adityaarora.liveedgedetection.view.ScanSurfaceView$3.onTick(ScanSurfaceView.java:296)`
    `at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:133)`
    `at android.os.Handler.dispatchMessage(Handler.java:102)`
    `at android.os.Looper.loop(Looper.java:154)`
    `at android.app.ActivityThread.main(ActivityThread.java:6123)`

        at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Comment by vinisauter** [comment]
Duplicate of #3

**Comment by abhatnagar03** [comment]
Closing as duplicate
