### ISSUE TITLE
Is it possible to enable reject button on cropping screen?

### ISSUE THREAD

**Issue by kazambrano** [adityaarora1/LiveEdgeDetection#20]
Is it possible or do you have an existing setting to make that button visible? I imported your project by gradle and only the check button appears on the cropping screen unlike when I downloaded your whole git project the reject button appears when I run it. 
You have a reject button here: https://github.com/adityaarora1/LiveEdgeDetection/blob/master/liveedgedetection/src/main/res/layout/activity_scan.xml

I wanted to restart scanning when the user taps on reject.

**Comment by adityaarora1** [comment]
Check the latest version and open a new request for change.
