### ISSUE TITLE
Support for newer versions

### ISSUE THREAD

**Issue by tarandeeptmsfalcon** [adityaarora1/LiveEdgeDetection#21]
I am trying to use this on Api version 28 but the camera seems not to be working. Can you suggest the possible solution?Camera is just black/white screen

**Comment by rmeph13** [comment]
same problem in my side....plz share if have any solution................

**Comment by zakblacki** [comment]
It works fine you must changed something

**Comment by adityaarora1** [comment]
Check the latest version.
