### ISSUE TITLE
How to build timeout for autofocus OCR 

### ISSUE THREAD

**Issue by zakblacki** [adityaarora1/LiveEdgeDetection#36]
Sometimes the image saved get blurry because of the autofocus wasn't ready Is there anyway to make constraint for the algorithm to detect OCR image ?

**Comment by zakblacki** [comment]
Hope we get a flutter version of this !

**Comment by adityaarora1** [comment]
Focus depends on the camera. The library depends on edge detection mechanism of OpenCV.
