### ISSUE TITLE
API 28 Live Preview Issue

### ISSUE THREAD

**Issue by gyleg5** [adityaarora1/LiveEdgeDetection#9]
On Android 9 the camera preview shows a white screen and not the camera feed.  The doc detection still works however.

![device-2018-09-26-125054](https://user-images.githubusercontent.com/18405154/46099313-7231ff80-c194-11e8-8904-b9219c8a17a4.png)

**Comment by JaydeeSale** [comment]
Any update on this i'm having the same issue with android 9

**Comment by pavlo-hrytsiuk** [comment]
Hi
There is something wrong with preview size, witch set  in ScanSurfaceView in surfaceChanged method
I changed it to:
        if (previewSize == null) {
            previewSize = camera.getParameters().getPreviewSize();
        }
//        if (previewSize == null)
//            previewSize = ScanUtils.getOptimalPreviewSize(camera, vWidth, vHeight);

it works

**Comment by ghost** [comment]
@PavloHrytsiuk where do I do this?

**Comment by hannesa2** [comment]
@PavloHrytsiuk Yes, when I follow your suggestion

![image](https://user-images.githubusercontent.com/3314607/57190280-cfefac80-6f18-11e9-9f3c-2fd22bcdcf2e.png)

I see the preview 👍 

As follow up issue, the captured image has a wrong orientation 👎 
![image](https://user-images.githubusercontent.com/3314607/57190329-3248ad00-6f19-11e9-96c2-58da05728885.png)

and the captured image contains simply all --> this is no solution 👎 
![image](https://user-images.githubusercontent.com/3314607/57190370-a4b98d00-6f19-11e9-8ab5-bc7f6777a3ed.png)

**Comment by rmeph13** [comment]
im having same problem....any solution...

**Comment by adityaarora1** [comment]
Please check the latest version and create an issue if it still persists.
